import { Product, Order, OrderStatus, User, UserRole, WarehouseStructure, Entity, EntityType, AuditLogEntry, Category, Supplier } from './types';

export const WAREHOUSE_STRUCTURE: WarehouseStructure = {
  'Almacén General': {
    'Sección A': ['Fila 1', 'Fila 2', 'Fila 3'],
    'Sección B': ['Fila 1', 'Fila 2'],
  },
  'Refrigerado': {
    'Sección C': ['Fila 1'],
  },
  'Materiales Peligrosos': {
    'Zona D': ['Estante 1', 'Estante 2'],
  }
};

export const MOCK_ENTITIES: Entity[] = [
  { 
    id: 'ent_A', 
    name: 'Empresa A', 
    type: EntityType.MyPime, 
    exchangeRate: 120, 
    isStoreEnabled: true,
    storeLogoUrl: 'https://picsum.photos/seed/logoA/200/200',
    storeCoverUrl: 'https://picsum.photos/seed/coverA/1200/400',
    storePriceMarkup: 25,
    storeSlug: 'tienda-empresa-a',
  },
  { id: 'ent_B', name: 'Empresa B', type: EntityType.Estatal, exchangeRate: 250, isStoreEnabled: false },
];

export const MOCK_CATEGORIES: Category[] = [
  // Empresa A
  { id: 'cat_A_1', entityId: 'ent_A', name: 'Electrónica' },
  { id: 'cat_A_2', entityId: 'ent_A', name: 'Periféricos' },
  { id: 'cat_A_3', entityId: 'ent_A', name: 'Mantenimiento' },
  { id: 'cat_A_4', entityId: 'ent_A', name: 'Alimentos' },
  // Empresa B
  { id: 'cat_B_1', entityId: 'ent_B', name: 'Monitores' },
  { id: 'cat_B_2', entityId: 'ent_B', name: 'Periféricos' },
  { id: 'cat_B_3', entityId: 'ent_B', name: 'Mobiliario' },
  { id: 'cat_B_4', entityId: 'ent_B', name: 'Construcción' },
];

export const MOCK_SUPPLIERS: Supplier[] = [
  // Empresa A
  { id: 'sup_A_1', entityId: 'ent_A', name: 'TechSupplier Inc.' },
  { id: 'sup_A_2', entityId: 'ent_A', name: 'GadgetMasters' },
  { id: 'sup_A_3', entityId: 'ent_A', name: 'ComfortTech' },
  { id: 'sup_A_4', entityId: 'ent_A', name: 'LubriCorp' },
  { id: 'sup_A_5', entityId: 'ent_A', name: 'Lácteos S.A.' },
  // Empresa B
  { id: 'sup_B_1', entityId: 'ent_B', name: 'Visionary Displays' },
  { id: 'sup_B_2', entityId: 'ent_B', name: 'SoundScape' },
  { id: 'sup_B_3', entityId: 'ent_B', name: 'ComfortTech' },
  { id: 'sup_B_4', entityId: 'ent_B', name: 'Constructora Principal' },
];

export const MOCK_PRODUCTS: Product[] = [
  // Empresa A
  {
    id: 'prod_001',
    entityId: 'ent_A',
    name: 'Laptop Gamer Avanzada',
    sku: 'LP-GM-X9',
    categoryId: 'cat_A_1',
    quantity: 15,
    unitOfMeasure: 'unidades',
    price: 1200.00,
    reorderPoint: 20,
    rating: 5,
    location: { warehouseType: 'Almacén General', section: 'Sección A', row: 'Fila 1' },
    supplierId: 'sup_A_1',
    addedDate: '2023-10-26T10:00:00Z',
    imageUrl: 'https://picsum.photos/seed/laptop/200/200',
    isPublished: true,
    storePrice: 1550.00,
  },
  {
    id: 'prod_002',
    entityId: 'ent_A',
    name: 'Teclado Mecánico RGB',
    sku: 'KB-RGB-01',
    categoryId: 'cat_A_2',
    quantity: 120,
    unitOfMeasure: 'unidades',
    price: 79.99,
    reorderPoint: 50,
    rating: 4,
    location: { warehouseType: 'Almacén General', section: 'Sección B', row: 'Fila 2' },
    supplierId: 'sup_A_2',
    addedDate: '2023-10-25T14:30:00Z',
    imageUrl: 'https://picsum.photos/seed/keyboard/200/200',
    isPublished: true,
    storePrice: 105.00,
  },
  {
    id: 'prod_003',
    entityId: 'ent_A',
    name: 'Mouse Inalámbrico Ergonómico',
    sku: 'MS-WL-E2',
    categoryId: 'cat_A_2',
    quantity: 250,
    unitOfMeasure: 'unidades',
    price: 49.50,
    rating: 5,
    location: { warehouseType: 'Almacén General', section: 'Sección A', row: 'Fila 1' },
    supplierId: 'sup_A_3',
    addedDate: '2023-10-25T11:00:00Z',
    imageUrl: 'https://picsum.photos/seed/mouse/200/200',
    isPublished: false,
  },
  // Empresa B
  {
    id: 'prod_004',
    entityId: 'ent_B',
    name: 'Monitor Curvo 27" 4K',
    sku: 'MN-CRV-4K',
    categoryId: 'cat_B_1',
    quantity: 40,
    unitOfMeasure: 'unidades',
    price: 450.00,
    reorderPoint: 15,
    rating: 4,
    location: { warehouseType: 'Refrigerado', section: 'Sección C', row: 'Fila 1' },
    supplierId: 'sup_B_1',
    addedDate: '2023-10-24T09:00:00Z',
    imageUrl: 'https://picsum.photos/seed/monitor/200/200',
  },
  {
    id: 'prod_005',
    entityId: 'ent_B',
    name: 'Auriculares con Cancelación de Ruido',
    sku: 'HP-NC-PRO',
    categoryId: 'cat_B_2',
    quantity: 150,
    unitOfMeasure: 'unidades',
    price: 199.99,
    rating: 5,
    location: { warehouseType: 'Almacén General', section: 'Sección B', row: 'Fila 1' },
    supplierId: 'sup_B_2',
    addedDate: '2023-10-23T16:45:00Z',
    imageUrl: 'https://picsum.photos/seed/headphones/200/200',
  },
  {
    id: 'prod_006',
    entityId: 'ent_B',
    name: 'Silla de Oficina Ergonómica',
    sku: 'CH-ERGO-X',
    categoryId: 'cat_B_3',
    quantity: 60,
    unitOfMeasure: 'unidades',
    price: 275.00,
    reorderPoint: 10,
    rating: 3,
    location: { warehouseType: 'Almacén General', section: 'Sección A', row: 'Fila 3' },
    supplierId: 'sup_B_3',
    addedDate: '2023-10-22T13:00:00Z',
    imageUrl: 'https://picsum.photos/seed/chair/200/200',
  },
  {
    id: 'prod_007',
    entityId: 'ent_A',
    name: 'Drone de Fotografía 4K',
    sku: 'DRN-PH-4K',
    serialNumber: 'SN-DRN-987654',
    inventoryNumber: 'INV-DRN-112233',
    categoryId: 'cat_A_1',
    quantity: 1,
    unitOfMeasure: 'unidades',
    price: 850.00,
    reorderPoint: 5,
    rating: 5,
    location: { warehouseType: 'Almacén General', section: 'Sección B', row: 'Fila 1' },
    supplierId: 'sup_A_1',
    addedDate: '2023-10-29T15:00:00Z',
    imageUrl: 'https://picsum.photos/seed/drone/200/200',
  },
  {
    id: 'prod_008',
    entityId: 'ent_A',
    name: 'Aceite Lubricante Industrial',
    sku: 'OIL-IND-5L',
    categoryId: 'cat_A_3',
    quantity: 50.5,
    unitOfMeasure: 'litros',
    price: 25.00,
    rating: 4,
    location: { warehouseType: 'Materiales Peligrosos', section: 'Zona D', row: 'Estante 1' },
    supplierId: 'sup_A_4',
    addedDate: '2023-10-30T10:00:00Z',
    imageUrl: 'https://picsum.photos/seed/oil/200/200',
    expirationDate: '2026-07-01T00:00:00Z',
  },
  {
    id: 'prod_009',
    entityId: 'ent_B',
    name: 'Polvo de Cemento',
    sku: 'CMT-P-25KG',
    categoryId: 'cat_B_4',
    quantity: 250.75,
    unitOfMeasure: 'kilogramos',
    price: 10.00,
    rating: 3,
    location: { warehouseType: 'Almacén General', section: 'Sección B', row: 'Fila 1' },
    supplierId: 'sup_B_4',
    addedDate: '2023-10-30T11:00:00Z',
    imageUrl: 'https://picsum.photos/seed/cement/200/200',
    expirationDate: '2024-05-01T00:00:00Z', // Expired
  },
  {
    id: 'prod_010',
    entityId: 'ent_A',
    name: 'Leche en Polvo',
    sku: 'LECH-P-1KG',
    categoryId: 'cat_A_4',
    quantity: 100,
    unitOfMeasure: 'kilogramos',
    price: 8.50,
    reorderPoint: 25,
    rating: 4,
    location: { warehouseType: 'Almacén General', section: 'Sección A', row: 'Fila 2' },
    supplierId: 'sup_A_5',
    addedDate: '2024-06-15T00:00:00Z',
    imageUrl: 'https://picsum.photos/seed/milk/200/200',
    expirationDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(), // ~15 days from now
  },
];

export const MOCK_ORDERS: Order[] = [
  // Empresa A
  {
    id: 'ORD-2023-001',
    entityId: 'ent_A',
    userId: 'user_normal_01_A',
    orderDate: '2023-10-28T10:30:00Z',
    status: OrderStatus.Shipped,
    total: 1200.00,
    items: [{ productId: 'prod_001', quantity: 1 }],
  },
  {
    id: 'ORD-2023-002',
    entityId: 'ent_A',
    userId: 'user_almacenero_01_A',
    orderDate: '2023-10-28T09:15:00Z',
    status: OrderStatus.Processing,
    total: 129.49,
    items: [
      { productId: 'prod_002', quantity: 1 },
      { productId: 'prod_003', quantity: 1 },
    ],
  },
   // Empresa B
  {
    id: 'ORD-2023-003',
    entityId: 'ent_B',
    userId: 'user_normal_01_B',
    orderDate: '2023-10-27T18:00:00Z',
    status: OrderStatus.Delivered,
    total: 450.00,
    items: [{ productId: 'prod_004', quantity: 1 }],
  },
  {
    id: 'ORD-2023-004',
    entityId: 'ent_B',
    userId: 'user_normal_01_B',
    orderDate: '2023-10-27T15:20:00Z',
    status: OrderStatus.Pending,
    total: 199.99,
    items: [{ productId: 'prod_005', quantity: 1 }],
  },
  {
    id: 'ORD-2023-005',
    entityId: 'ent_B',
    userId: 'user_normal_01_B',
    orderDate: '2023-10-26T11:45:00Z',
    status: OrderStatus.Cancelled,
    total: 275.00,
    items: [{ productId: 'prod_006', quantity: 1 }],
  },
  {
    id: 'ORD-2023-006',
    entityId: 'ent_A',
    userId: 'user_normal_01_A',
    orderDate: '2023-10-29T11:00:00Z',
    status: OrderStatus.Pending,
    total: 1249.50,
    items: [
        { productId: 'prod_001', quantity: 1 },
        { productId: 'prod_003', quantity: 1 },
    ],
  },
];

export const MOCK_USERS: User[] = [
    // System Users
    {
        id: 'user_super_usuario_01',
        entityId: 'sys_root',
        name: 'void',
        email: 'void',
        role: UserRole.SuperUsuario,
        avatarUrl: 'https://i.pravatar.cc/150?u=superusuario',
        password: '456',
    },
    {
        id: 'user_super_admin_01',
        entityId: 'sys_admin',
        name: 'Super Admin',
        email: 'adm',
        role: UserRole.SuperAdmin,
        avatarUrl: 'https://i.pravatar.cc/150?u=superadmin',
        password: '123',
    },
    // Empresa A
    {
        id: 'user_admin_01_A',
        entityId: 'ent_A',
        name: 'Mario López (Admin A)',
        email: 'admin',
        role: UserRole.Admin,
        avatarUrl: 'https://picsum.photos/seed/userA1/100/100',
        password: '123',
    },
    {
        id: 'user_almacenero_01_A',
        entityId: 'ent_A',
        name: 'Juan Pérez (Almacenero A)',
        email: 'juan.perez@empresa_a.com',
        role: UserRole.Almacenero,
        avatarUrl: 'https://picsum.photos/seed/userA2/100/100',
        password: 'almacen123',
    },
    {
        id: 'user_normal_01_A',
        entityId: 'ent_A',
        name: 'Carla Rivas (Usuario A)',
        email: 'carla.rivas@empresa_a.com',
        role: UserRole.User,
        avatarUrl: 'https://picsum.photos/seed/userA3/100/100',
        password: 'user123',
    },
    // Empresa B
    {
        id: 'user_admin_01_B',
        entityId: 'ent_B',
        name: 'Beatriz Solis (Admin B)',
        email: 'admin_b',
        role: UserRole.Admin,
        avatarUrl: 'https://picsum.photos/seed/userB1/100/100',
        password: '123',
    },
    {
        id: 'user_almacenero_01_B',
        entityId: 'ent_B',
        name: 'Luis Castro (Almacenero B)',
        email: 'luis.castro@empresa_b.com',
        role: UserRole.Almacenero,
        avatarUrl: 'https://picsum.photos/seed/userB3/100/100',
        password: 'almacen123',
    },
     {
        id: 'user_normal_01_B',
        entityId: 'ent_B',
        name: 'Pedro Gomez (Usuario B)',
        email: 'pedro.gomez@empresa_b.com',
        role: UserRole.User,
        avatarUrl: 'https://picsum.photos/seed/userB2/100/100',
        password: 'user123',
    }
];

export const MOCK_AUDIT_LOGS: AuditLogEntry[] = [
    {
        id: 'log_1',
        entityId: 'ent_A',
        userId: 'user_almacenero_01_A',
        timestamp: '2023-10-29T15:00:00Z',
        action: 'Creó el nuevo producto "Drone de Fotografía 4K".',
    },
    {
        id: 'log_2',
        entityId: 'ent_A',
        userId: 'user_almacenero_01_A',
        timestamp: '2023-10-28T09:15:00Z',
        action: 'Actualizó el estado del pedido ORD-2023-002 a Procesando.',
    },
    {
        id: 'log_3',
        entityId: 'ent_B',
        userId: 'user_almacenero_01_B',
        timestamp: '2023-10-27T10:00:00Z',
        action: 'Actualizó la cantidad del producto "Monitor Curvo 27" 4K" a 40 unidades.',
    },
    {
        id: 'log_4',
        entityId: 'ent_B',
        userId: 'user_almacenero_01_B',
        timestamp: '2023-10-27T18:05:00Z',
        action: 'Actualizó el estado del pedido ORD-2023-003 a Entregado.',
    }
];